CREATE TABLE role (
  id NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1),
  name VARCHAR2(45) DEFAULT NULL,
  PRIMARY KEY (id));

CREATE  TABLE users (
  id NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1),
  username VARCHAR2(255) DEFAULT NULL,
  password VARCHAR2(255) DEFAULT NULL,
  PRIMARY KEY (id));

CREATE TABLE user_role (
  user_id NUMBER NOT NULL,
  role_id NUMBER NOT NULL,
  PRIMARY KEY (user_id, role_id)
);

CREATE INDEX fk_user_role_roleid_idx ON USER_ROLE(role_id);
ALTER TABLE user_role
  ADD CONSTRAINT fk_user_role_roleid FOREIGN KEY (role_id) REFERENCES role (id) ON DELETE CASCADE;
ALTER TABLE user_role
  ADD	CONSTRAINT fk_user_role_userid FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;